# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
[versions]
spring-boot = "4.0.2"
spring-dependency-management = "1.1.7"
kotlin-core = "2.3.0"
springdoc = "3.0.1"
spotless = "8.2.0"
mockito-kotlin = "6.2.3"
wiremock-spring-boot = "4.0.9"
scrimage = "4.3.5"

[libraries]
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
apache-httpclient = { module = "org.apache.httpcomponents.client5:httpclient5" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
scrimage-core = { module = "com.sksamuel.scrimage:scrimage-core", version.ref = "scrimage" }
springdoc-openapi-webmvc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
wiremock-spring-boot = { module = "org.wiremock.integrations:wiremock-spring-boot", version.ref = "wiremock-spring-boot" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spottless = { id = "com.diffplug.spotless", version.ref = "spotless" }